# Generated by Django 3.2 on 2022-08-02 09:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=512, verbose_name='URL')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('url',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=512, verbose_name='URL')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('last_fetched', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('url',),
                'unique_together': {('start_date', 'url')},
            },
        ),
    ]
